### ISSUE TITLE
Call to github is too greedy

### ISSUE THREAD

**Issue by mcdonnelldean** [nodezoo/nodezoo-github#45]
We don't need much of the data that is being return, we need to see if we can narrow the terms we are sending and reduce the data to the minimum required to satisfy our requirements.

**Comment by mcdonnelldean** [comment]
@CodeWriterWriter May as well assign this to you since you are working on changing the client.

**Comment by CodeWriterWriter** [comment]
I've looked into the API call we're making to get our information, and some information we're getting can only be gotten from that singular call, some we can get or or infer from other calls, but if we have the one call doing everything doesn't make sense to add lots of smaller ones.

**Comment by mcdonnelldean** [comment]
What we gain on the one we will loose on the other. Since we are using a client there ain't too much we can do. Not to worry :D
