### ISSUE TITLE
github url now broken

### ISSUE THREAD

**Issue by matt-oc** [nodezoo/nodezoo-github#57]
I think @mcdonnelldean got a bit too exuberant with the tidying and removed the code to format the url correctly :grin:

**Comment by mcdonnelldean** [comment]
These are the ones I have,

```        
urlRepo: msg.url || '',
urlClone: repo.clone_url || '',
```

These two return valid data. The names are reversed though.

**Comment by matt-oc** [comment]
Yes but the formatting is incorrect for copying and using, we found out a few months ago that what is returned can be loads of different formats, some work some don't so it needs code to manually do it for reliability. We also don't need a clone url, its the same as the normal one :smile:

**Comment by mcdonnelldean** [comment]
Thats not correct. There should be two urls, one for the project location and one for the code.

**Comment by matt-oc** [comment]
Yea? the normal url works fine for cloning and pushing etc, we tested it out

**Comment by mcdonnelldean** [comment]
On Githb the difference is just adding .git at the end, but this is not always true, we need to have the concept of the url the repo lives and the url that is cloned from

**Comment by mcdonnelldean** [comment]
The copy version would be the clone, the link version is what you use against the button to go to github.

**Comment by matt-oc** [comment]
I guess it makes sense in the case repos will be stored somewhere other than github where it may not work the same

**Comment by mcdonnelldean** [comment]
@matt-oc Having one rule for some and another rule for others is confusing. The concept of a clone url vs a project url is well known. What part of this url scheme breaks for you?

**Comment by mcdonnelldean** [comment]
We basically need these:

```
  "git_url": "git:\/\/github.com\/lodash\/lodash.git",
  "ssh_url": "git@github.com:lodash\/lodash.git",
  "clone_url": "https:\/\/github.com\/lodash\/lodash.git",
```

**Comment by matt-oc** [comment]
@mcdonnelldean thats ok I can roll with that, the issue is from github the url can come in the format: https://github.com/nodezoo which is great but it also come like this:

ssh://git@<modulename> and 
git@github.com:user/module etc

and these dont work properly due to how the git module returns them so they need manual formatting

**Comment by mcdonnelldean** [comment]
So they are different urls. They do different things. Were exactly are you using this url? the one that's broken?

**Comment by matt-oc** [comment]
When we call our git module to go get the repo it returns the url that you have assigned to url so sometimes the url will go out as ssh://git@nodezoo.. etc which cant be used for cloning or as a link

**Comment by mcdonnelldean** [comment]
So this one is the problem: `urlClone: repo.clone_url || '',`

**Comment by matt-oc** [comment]
now fixed
