### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by powerbrian** [nodezoo/nodezoo-github#73]
5 of 6 tests here are failing

**Comment by mirceaalexandru** [comment]
We need to see how we can pass those tests, the features depends on github token

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Two options,

1: Put a token in Travis, this can be passed in via env variable and will work for tests.
2: Proxy the service using Proxyquire, better option but will take longer so maybe a future change?
