### ISSUE TITLE
NPM registry referenced instead of github

### ISSUE THREAD

**Issue by shaunwarman** [nodezoo/nodezoo-github#77]
It looks like npm is referenced instead of github [here] (https://github.com/nodezoo/nodezoo-github/blob/master/lib/github.js#L9)  and [here] (https://github.com/nodezoo/nodezoo-github/blob/master/srv/start.js#L16).

**Comment by mcdonnelldean** [comment]
This is to prove the module exists on npm since only npm modules are considered valid. The ability to swap the registery url is to allow private installations.

**Comment by shaunwarman** [comment]
Ah this makes perfect sense. Thanks!
